/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.7.41-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `medicines_csv` (
	`È&ò` int (10),
	`'ò` varchar (765)
); 
insert into `medicines_csv` (`id`, `name`) values('1','Augmentin 625 Duo Tablet');
insert into `medicines_csv` (`id`, `name`) values('2','Azithral 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('3','Ascoril LS Syrup');
insert into `medicines_csv` (`id`, `name`) values('4','Allegra 120mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('5','Avil 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('6','Allegra-M Tablet');
insert into `medicines_csv` (`id`, `name`) values('7','Amoxyclav 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('8','Azee 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('9','Atarax 25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('10','Ascoril D Plus Syrup Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('11','Aciloc 150 Tablet');
insert into `medicines_csv` (`id`, `name`) values('12','Alex Syrup');
insert into `medicines_csv` (`id`, `name`) values('13','Anovate Cream');
insert into `medicines_csv` (`id`, `name`) values('14','Augmentin Duo Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('15','Ambrodil-S Syrup');
insert into `medicines_csv` (`id`, `name`) values('16','Arkamin Tablet');
insert into `medicines_csv` (`id`, `name`) values('17','Avomine Tablet');
insert into `medicines_csv` (`id`, `name`) values('18','Asthakind-DX Syrup Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('19','Allegra 180mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('20','Albendazole 400mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('21','Asthalin Syrup');
insert into `medicines_csv` (`id`, `name`) values('22','Alprax 0.25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('23','Altraday Capsule SR');
insert into `medicines_csv` (`id`, `name`) values('24','Ativan 2mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('25','Ascoril LS Junior Syrup');
insert into `medicines_csv` (`id`, `name`) values('26','Asthalin 100mcg Inhaler');
insert into `medicines_csv` (`id`, `name`) values('27','Almox 500 Capsule');
insert into `medicines_csv` (`id`, `name`) values('28','Atarax 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('29','Aciloc RD 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('30','Aldactone Tablet');
insert into `medicines_csv` (`id`, `name`) values('31','Allegra Suspension Raspberry & Vanilla');
insert into `medicines_csv` (`id`, `name`) values('32','Atarax Syrup');
insert into `medicines_csv` (`id`, `name`) values('33','Amlokind-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('34','Axcer  90mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('35','Ativan 1mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('36','Alkasol Oral Solution');
insert into `medicines_csv` (`id`, `name`) values('37','Aldigesic P 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('38','Alfoo 10mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('39','Alprax 0.5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('40','Arachitol 6L Injection');
insert into `medicines_csv` (`id`, `name`) values('41','Anafortan 25 mg/300 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('42','Alex Junior Syrup');
insert into `medicines_csv` (`id`, `name`) values('43','Azithral 200 Liquid');
insert into `medicines_csv` (`id`, `name`) values('44','AB Phylline Capsule');
insert into `medicines_csv` (`id`, `name`) values('45','Althrocin 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('46','Augmentin DDS Suspension');
insert into `medicines_csv` (`id`, `name`) values('47','Azicip 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('48','Aldigesic-SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('49','Amoxycillin 500mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('50','Asthakind Expectorant Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('51','Acemiz Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('52','Aceclo Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('53','Anobliss Cream');
insert into `medicines_csv` (`id`, `name`) values('54','Alex Cough Lozenges Lemon Ginger');
insert into `medicines_csv` (`id`, `name`) values('55','Asthalin Respules');
insert into `medicines_csv` (`id`, `name`) values('56','Avil Injection');
insert into `medicines_csv` (`id`, `name`) values('57','Azee 200mg Dry Syrup');
insert into `medicines_csv` (`id`, `name`) values('58','Atorva Tablet');
insert into `medicines_csv` (`id`, `name`) values('59','Asthakind-LS Expectorant Cola Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('60','Ascoril LS Drops');
insert into `medicines_csv` (`id`, `name`) values('61','Azmarda 50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('62','Amixide-H Tablet');
insert into `medicines_csv` (`id`, `name`) values('63','AB-Flo-N Tablet');
insert into `medicines_csv` (`id`, `name`) values('64','AF Kit Tablet');
insert into `medicines_csv` (`id`, `name`) values('65','Amlokind 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('66','Amlong Tablet');
insert into `medicines_csv` (`id`, `name`) values('67','Akt 4 Kit');
insert into `medicines_csv` (`id`, `name`) values('68','Ascoril D Junior Cough Syrup');
insert into `medicines_csv` (`id`, `name`) values('69','Amitone 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('70','Aulin 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('71','Amikacin Sulphate 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('72','Ambrodil-LX Syrup');
insert into `medicines_csv` (`id`, `name`) values('73','Aquasol A Capsule');
insert into `medicines_csv` (`id`, `name`) values('74','AB Phylline SR 200 Tablet');
insert into `medicines_csv` (`id`, `name`) values('75','Azoran Tablet');
insert into `medicines_csv` (`id`, `name`) values('76','Amaryl 1mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('77','Aztor 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('78','Atorva 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('79','Azax 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('80','Alex Syrup Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('81','Anxit 0.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('82','Anxit 0.25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('83','Acitrom 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('84','Angispan - TR 2.5mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('85','Azeflo Nasal Spray');
insert into `medicines_csv` (`id`, `name`) values('86','Acemiz -MR Tablet');
insert into `medicines_csv` (`id`, `name`) values('87','Akurit 4 Tablet');
insert into `medicines_csv` (`id`, `name`) values('88','Aerocort Inhaler');
insert into `medicines_csv` (`id`, `name`) values('89','Adaferin Gel');
insert into `medicines_csv` (`id`, `name`) values('90','Acivir 400 DT Tablet');
insert into `medicines_csv` (`id`, `name`) values('91','Aptimust Syrup');
insert into `medicines_csv` (`id`, `name`) values('92','Augmentin 1000 Duo Tablet');
insert into `medicines_csv` (`id`, `name`) values('93','Ambrodil Syrup');
insert into `medicines_csv` (`id`, `name`) values('94','Acogut Tablet');
insert into `medicines_csv` (`id`, `name`) values('95','Atarax Drops');
insert into `medicines_csv` (`id`, `name`) values('96','Amlip 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('97','AntiD 300mcg/ml Injection');
insert into `medicines_csv` (`id`, `name`) values('98','Alerid Syrup');
insert into `medicines_csv` (`id`, `name`) values('99','Aldactone 50 Tablet');
insert into `medicines_csv` (`id`, `name`) values('100','Ampoxin 500 Capsule');
insert into `medicines_csv` (`id`, `name`) values('101','Azee 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('102','Alerid Tablet');
insert into `medicines_csv` (`id`, `name`) values('103','Augmentin 375 Tablet');
insert into `medicines_csv` (`id`, `name`) values('104','Acenac-P  Tablet');
insert into `medicines_csv` (`id`, `name`) values('105','Acivir Cream');
insert into `medicines_csv` (`id`, `name`) values('106','AB-Flo Capsule');
insert into `medicines_csv` (`id`, `name`) values('107','AB Phylline N Tablet');
insert into `medicines_csv` (`id`, `name`) values('108','Amifru 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('109','Avamys Nasal Spray');
insert into `medicines_csv` (`id`, `name`) values('110','Alkasol Oral Solution Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('111','Aciloc 300 Tablet');
insert into `medicines_csv` (`id`, `name`) values('112','Aziderm 20% Cream');
insert into `medicines_csv` (`id`, `name`) values('113','Ace Proxyvon Tablet');
insert into `medicines_csv` (`id`, `name`) values('114','Avil Injection');
insert into `medicines_csv` (`id`, `name`) values('115','Ano Metrogyl Cream');
insert into `medicines_csv` (`id`, `name`) values('116','Admenta 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('117','Aceclo-MR Tablet');
insert into `medicines_csv` (`id`, `name`) values('118','Alerid-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('119','Acemiz-S Tablet');
insert into `medicines_csv` (`id`, `name`) values('120','Allercet-DC Tablet');
insert into `medicines_csv` (`id`, `name`) values('121','Aztolet  10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('122','Amaryl 2mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('123','Augmentin 1.2gm Injection');
insert into `medicines_csv` (`id`, `name`) values('124','Ambrodil-Plus RF Syrup');
insert into `medicines_csv` (`id`, `name`) values('125','Amlopres-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('126','Ajaduo 25mg/5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('127','Avanair 100 Tablet');
insert into `medicines_csv` (`id`, `name`) values('128','Acton-OR Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('129','Aquazide 12.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('130','Alaspan AM Tablet');
insert into `medicines_csv` (`id`, `name`) values('131','Althrocin 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('132','Azikem 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('133','Aldosmin 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('134','Amlovas 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('135','Acitrom 1 Tablet');
insert into `medicines_csv` (`id`, `name`) values('136','AF 150 Tablet DT');
insert into `medicines_csv` (`id`, `name`) values('137','Ascoril SF Expectorant');
insert into `medicines_csv` (`id`, `name`) values('138','Amaryl M  1mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('139','Azithral XL 200 Liquid');
insert into `medicines_csv` (`id`, `name`) values('140','AF 400 Tablet');
insert into `medicines_csv` (`id`, `name`) values('141','Amantrel Tablet');
insert into `medicines_csv` (`id`, `name`) values('142','Atorva 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('143','Acenac-MR Tablet');
insert into `medicines_csv` (`id`, `name`) values('144','Ambrolite-S Expectorant');
insert into `medicines_csv` (`id`, `name`) values('145','Asthalin 4 Tablet');
insert into `medicines_csv` (`id`, `name`) values('146','Abiways Tablet');
insert into `medicines_csv` (`id`, `name`) values('147','Amaryl M  2mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('148','Azoran Tablet');
insert into `medicines_csv` (`id`, `name`) values('149','Ampilox Capsule');
insert into `medicines_csv` (`id`, `name`) values('150','Adrenaline Tartrate Injection');
insert into `medicines_csv` (`id`, `name`) values('151','Acogut 300 ER Tablet');
insert into `medicines_csv` (`id`, `name`) values('152','Acuvin Tablet');
insert into `medicines_csv` (`id`, `name`) values('153','AB-Flo SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('154','Air-M Tablet');
insert into `medicines_csv` (`id`, `name`) values('155','Atorlip-F Tablet');
insert into `medicines_csv` (`id`, `name`) values('156','Advent Forte 457mg Syrup Tangy Orange');
insert into `medicines_csv` (`id`, `name`) values('157','Amlodac 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('158','Aztor 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('159','Ascoril Plus Expectorant');
insert into `medicines_csv` (`id`, `name`) values('160','Alupent 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('161','Amlip AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('162','Asthakind-P Drops');
insert into `medicines_csv` (`id`, `name`) values('163','Allegra Nasal Spray');
insert into `medicines_csv` (`id`, `name`) values('164','Addnok 0.2mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('165','Aldosmin 1000mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('166','Andre I-Kul Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('167','Antiflu 75mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('168','Alerfix Total Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('169','Alex-L Cough Syrup Mango');
insert into `medicines_csv` (`id`, `name`) values('170','Atropine Sulphate Injection');
insert into `medicines_csv` (`id`, `name`) values('171','Aquaviron Injection 1ml');
insert into `medicines_csv` (`id`, `name`) values('172','Aciclovir 400 Tablet');
insert into `medicines_csv` (`id`, `name`) values('173','Alkof DX Syrup');
insert into `medicines_csv` (`id`, `name`) values('174','ATM 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('175','Assurans Tablet');
insert into `medicines_csv` (`id`, `name`) values('176','Ambrolite D Syrup');
insert into `medicines_csv` (`id`, `name`) values('177','Actrapid HM 100IU/ml Penfill');
insert into `medicines_csv` (`id`, `name`) values('178','Aten 50 Tablet');
insert into `medicines_csv` (`id`, `name`) values('179','Azmarda 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('180','Asthalin AX Syrup');
insert into `medicines_csv` (`id`, `name`) values('181','Alzolam 0.5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('182','A Kare Combipack');
insert into `medicines_csv` (`id`, `name`) values('183','Ambulax Tablet');
insert into `medicines_csv` (`id`, `name`) values('184','Amlovas-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('185','Asthakind-DX Junior Syrup Cherry');
insert into `medicines_csv` (`id`, `name`) values('186','Advent 228.5mg Dry Syrup');
insert into `medicines_csv` (`id`, `name`) values('187','Acivir 800 DT Tablet');
insert into `medicines_csv` (`id`, `name`) values('188','Alfusin Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('189','Aziwok 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('190','Alkacitral Liquid');
insert into `medicines_csv` (`id`, `name`) values('191','Almox-CV 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('192','Azithral 100 Liquid');
insert into `medicines_csv` (`id`, `name`) values('193','Azee 100mg Dry Syrup Peppermint');
insert into `medicines_csv` (`id`, `name`) values('194','Ace-Proxyvon CR Tablet');
insert into `medicines_csv` (`id`, `name`) values('195','Ascoril C  Syrup');
insert into `medicines_csv` (`id`, `name`) values('196','Aprezo 30mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('197','Apidra 100IU Cartridge');
insert into `medicines_csv` (`id`, `name`) values('198','Amlosafe 3D Tablet');
insert into `medicines_csv` (`id`, `name`) values('199','Andial 2mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('200','Acenext P 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('201','Acnesol A Nano Gel');
insert into `medicines_csv` (`id`, `name`) values('202','Ascoril Flu Syrup');
insert into `medicines_csv` (`id`, `name`) values('203','Asomex 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('204','Angiplat 2.5 Capsule TR');
insert into `medicines_csv` (`id`, `name`) values('205','Alkof Cofgel  Tablet');
insert into `medicines_csv` (`id`, `name`) values('206','Azithral 250mg DT Tablet');
insert into `medicines_csv` (`id`, `name`) values('207','Alzolam 0.25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('208','Advent 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('209','Alsita M 50mg/500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('210','Axogurd-SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('211','Azoflox UTI Tablet');
insert into `medicines_csv` (`id`, `name`) values('212','Azulix 2 MF Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('213','Amaryl MV 2mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('214','Azulix 1 MF Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('215','Aten 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('216','Azibact 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('217','Amlopres TL Tablet');
insert into `medicines_csv` (`id`, `name`) values('218','Ambrolite Syrup');
insert into `medicines_csv` (`id`, `name`) values('219','Actapro Tablet');
insert into `medicines_csv` (`id`, `name`) values('220','Aztor 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('221','Alkof Syrup');
insert into `medicines_csv` (`id`, `name`) values('222','Atorfit CV 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('223','Acnesol Gel');
insert into `medicines_csv` (`id`, `name`) values('224','Amtas 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('225','Alrgee 120mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('226','Avil 50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('227','Arip MT 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('228','Alivher Tablet');
insert into `medicines_csv` (`id`, `name`) values('229','Apdrops LP  Eye Drop BAK Free');
insert into `medicines_csv` (`id`, `name`) values('230','Amrox-LS Syrup');
insert into `medicines_csv` (`id`, `name`) values('231','Altonil 3mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('232','Allercet Cold Tablet');
insert into `medicines_csv` (`id`, `name`) values('233','Atorlip 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('234','Admenta 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('235','Amox 500mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('236','Azee 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('237','Asthalin Respirator Solution');
insert into `medicines_csv` (`id`, `name`) values('238','Add Tears Lubricant Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('239','Almox 250 Capsule');
insert into `medicines_csv` (`id`, `name`) values('240','Aztor Asp 75 Capsule');
insert into `medicines_csv` (`id`, `name`) values('241','Alkacip Syrup');
insert into `medicines_csv` (`id`, `name`) values('242','Arbitel-Trio 50 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('243','Acivir 200 DT Tablet');
insert into `medicines_csv` (`id`, `name`) values('244','Augmentin ES Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('245','Amrolstar Cream');
insert into `medicines_csv` (`id`, `name`) values('246','Adalene Nanogel Gel');
insert into `medicines_csv` (`id`, `name`) values('247','Apigat 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('248','Aeromont-B Tablet');
insert into `medicines_csv` (`id`, `name`) values('249','Amlopres 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('250','Abevia-N Tablet');
insert into `medicines_csv` (`id`, `name`) values('251','Acamprol Tablet');
insert into `medicines_csv` (`id`, `name`) values('252','Ancool  Oral Suspension Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('253','Atormac CV10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('254','Apdrops PD Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('255','Amnurite  10 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('256','Atonide Gel');
insert into `medicines_csv` (`id`, `name`) values('257','Amlong-A Tablet');
insert into `medicines_csv` (`id`, `name`) values('258','Acivir 500 Infusion');
insert into `medicines_csv` (`id`, `name`) values('259','AF-K Lotion');
insert into `medicines_csv` (`id`, `name`) values('260','Amoxyclav 375 Tablet');
insert into `medicines_csv` (`id`, `name`) values('261','Abd 400mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('262','Amlong 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('263','Alburel 20gm Solution for Infusion');
insert into `medicines_csv` (`id`, `name`) values('264','Anacin Tablet');
insert into `medicines_csv` (`id`, `name`) values('265','Azithro 250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('266','Azimax 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('267','Amlosafe-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('268','Air 180 Tablet');
insert into `medicines_csv` (`id`, `name`) values('269','Adilip 135 Tablet DR');
insert into `medicines_csv` (`id`, `name`) values('270','Apdrops Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('271','Amlosafe 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('272','Apigat 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('273','Amlogard 5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('274','Amaryl MV 1mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('275','Azee 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('276','ALERGIN L TABLET');
insert into `medicines_csv` (`id`, `name`) values('277','Aciloc Injection');
insert into `medicines_csv` (`id`, `name`) values('278','Alex P Syrup');
insert into `medicines_csv` (`id`, `name`) values('279','AZR Tablet');
insert into `medicines_csv` (`id`, `name`) values('280','Angicam-Beta Tablet');
insert into `medicines_csv` (`id`, `name`) values('281','Amicobal 10mg/1500mcg Tablet');
insert into `medicines_csv` (`id`, `name`) values('282','Actibile 300 Tablet');
insert into `medicines_csv` (`id`, `name`) values('283','Ambrolite Levo Syrup');
insert into `medicines_csv` (`id`, `name`) values('284','Amaryl M Forte 2mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('285','Acivir Cream');
insert into `medicines_csv` (`id`, `name`) values('286','Azicip 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('287','Algesia CR 200mg/20mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('288','Ascoril Expectorant');
insert into `medicines_csv` (`id`, `name`) values('289','Atorva 80 Tablet');
insert into `medicines_csv` (`id`, `name`) values('290','Acitrom 4 Tablet');
insert into `medicines_csv` (`id`, `name`) values('291','Alsita 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('292','Amnurite  5 mg/1500 mcg Tablet');
insert into `medicines_csv` (`id`, `name`) values('293','Airz Capsule');
insert into `medicines_csv` (`id`, `name`) values('294','Asomex 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('295','Axcer  90mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('296','Anaspas Tablet');
insert into `medicines_csv` (`id`, `name`) values('297','Ascabiol Emulsion');
insert into `medicines_csv` (`id`, `name`) values('298','Addwize 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('299','Ascoril Plus Expectorant');
insert into `medicines_csv` (`id`, `name`) values('300','Amlong 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('301','Abd Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('302','Allercet-M Tablet');
insert into `medicines_csv` (`id`, `name`) values('303','Augpen -DS Suspension');
insert into `medicines_csv` (`id`, `name`) values('304','Althrocin Liquid');
insert into `medicines_csv` (`id`, `name`) values('305','Atocor 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('306','Augpen 625 BID Tablet');
insert into `medicines_csv` (`id`, `name`) values('307','Atchol-F Tablet');
insert into `medicines_csv` (`id`, `name`) values('308','Alensol-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('309','Arbitel-Trio 25 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('310','Acivir Eye Ointment');
insert into `medicines_csv` (`id`, `name`) values('311','Aceclo Tablet');
insert into `medicines_csv` (`id`, `name`) values('312','Actrapid 100 IU/ml Flexpen');
insert into `medicines_csv` (`id`, `name`) values('313','Amitone 25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('314','Anafortan Syrup');
insert into `medicines_csv` (`id`, `name`) values('315','Acera-D Capsule SR');
insert into `medicines_csv` (`id`, `name`) values('316','Aerodil SF Expectorant');
insert into `medicines_csv` (`id`, `name`) values('317','Aculip H 12.5 mg/5 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('318','Aztolet  20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('319','Amlopin 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('320','Arimidex 1mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('321','Alzil-M 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('322','Acuvert Tablet');
insert into `medicines_csv` (`id`, `name`) values('323','Alciflox 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('324','Azax 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('325','Aceclo Spas Tablet');
insert into `medicines_csv` (`id`, `name`) values('326','Asthakind-LS Drop');
insert into `medicines_csv` (`id`, `name`) values('327','Ascabiol Emulsion');
insert into `medicines_csv` (`id`, `name`) values('328','Alphadol 0.25mcg Capsule');
insert into `medicines_csv` (`id`, `name`) values('329','Alex Cough Lozenges Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('330','Arip MT 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('331','Anabel Liquid Gel');
insert into `medicines_csv` (`id`, `name`) values('332','Aricep 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('333','Amlosafe-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('334','Aceclo SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('335','Azopt Opthalmic Suspension');
insert into `medicines_csv` (`id`, `name`) values('336','Amitop 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('337','Ambulax M Tablet');
insert into `medicines_csv` (`id`, `name`) values('338','Alcipro 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('339','Assurans Tablet');
insert into `medicines_csv` (`id`, `name`) values('340','Augpen LB 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('341','Alkaliser Syrup');
insert into `medicines_csv` (`id`, `name`) values('342','Aquaviron 40mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('343','Angiwell 2.6mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('344','Anaflam TH  4  Tablet');
insert into `medicines_csv` (`id`, `name`) values('345','Alzil 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('346','Amlo 5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('347','Asthalin Plus Expectorant');
insert into `medicines_csv` (`id`, `name`) values('348','Ascabiol Emulsion');
insert into `medicines_csv` (`id`, `name`) values('349','Amitone Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('350','Akt 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('351','Alex Plus Paediatric Oral Drops');
insert into `medicines_csv` (`id`, `name`) values('352','Antacid Tablet');
insert into `medicines_csv` (`id`, `name`) values('353','Apresol Tablet');
insert into `medicines_csv` (`id`, `name`) values('354','Atchol 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('355','Amlong-H Tablet');
insert into `medicines_csv` (`id`, `name`) values('356','Airz-FF Capsule');
insert into `medicines_csv` (`id`, `name`) values('357','Arflur 3D Tablet');
insert into `medicines_csv` (`id`, `name`) values('358','Azmarda 200mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('359','Amixide 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('360','Avomine 25mg Tablet MD');
insert into `medicines_csv` (`id`, `name`) values('361','Arpizol 2mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('362','Ascodex Cough Syrup');
insert into `medicines_csv` (`id`, `name`) values('363','Aerocort Forte Rotacap');
insert into `medicines_csv` (`id`, `name`) values('364','AF 200 Tablet');
insert into `medicines_csv` (`id`, `name`) values('365','Aquasurge  Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('366','Atorva Asp 75 Capsule');
insert into `medicines_csv` (`id`, `name`) values('367','Azivent 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('368','Azithral Eye Ointment');
insert into `medicines_csv` (`id`, `name`) values('369','Adtrol XT Tablet');
insert into `medicines_csv` (`id`, `name`) values('370','Aqualube Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('371','Antisnake Venom Injection');
insert into `medicines_csv` (`id`, `name`) values('372','Acrotac 25mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('373','Azathioprine 50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('374','Amrolstar Nail Lacquer');
insert into `medicines_csv` (`id`, `name`) values('375','Allercet-M Syrup');
insert into `medicines_csv` (`id`, `name`) values('376','Atchol 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('377','Alphagan Z Ophthalmic Solution');
insert into `medicines_csv` (`id`, `name`) values('378','Acutret 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('379','Acnedap Gel');
insert into `medicines_csv` (`id`, `name`) values('380','Amoxycillin 125mg Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('381','Advanced LCF Kid Expectorant');
insert into `medicines_csv` (`id`, `name`) values('382','Amitryn 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('383','Amtas-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('384','Accentrix Solution for Injection');
insert into `medicines_csv` (`id`, `name`) values('385','Arpizol 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('386','Alkasol Oral Solution');
insert into `medicines_csv` (`id`, `name`) values('387','Aldactone 100 Tablet');
insert into `medicines_csv` (`id`, `name`) values('388','Aztogold 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('389','Addna Tablet');
insert into `medicines_csv` (`id`, `name`) values('390','Amtas-M 50 Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('391','Akilos-P Tablet');
insert into `medicines_csv` (`id`, `name`) values('392','Avas CV 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('393','Actilyse 50mg Injection');
insert into `medicines_csv` (`id`, `name`) values('394','Acceclowoc-SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('395','Amodep AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('396','Amlopres AT 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('397','Acular LS Ophthalmic Solution');
insert into `medicines_csv` (`id`, `name`) values('398','Anxipan Capsule');
insert into `medicines_csv` (`id`, `name`) values('399','Advent 91.4mg Drops Tangy Orange');
insert into `medicines_csv` (`id`, `name`) values('400','Azee XL 200mg Dry Syrup Peppermint');
insert into `medicines_csv` (`id`, `name`) values('401','Abevia 100 Capsule');
insert into `medicines_csv` (`id`, `name`) values('402','Alex Oral Drops Orange');
insert into `medicines_csv` (`id`, `name`) values('403','Amoxyclav DS Syrup');
insert into `medicines_csv` (`id`, `name`) values('404','Alcoliv Tablet');
insert into `medicines_csv` (`id`, `name`) values('405','Anosum Cream');
insert into `medicines_csv` (`id`, `name`) values('406','Amlovas-M 5/50 Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('407','Alkamax MB Alkamax MB6 Oral Solution');
insert into `medicines_csv` (`id`, `name`) values('408','Amlosafe TM 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('409','Apetamin Syrup');
insert into `medicines_csv` (`id`, `name`) values('410','Aceflam P 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('411','Ascovent -SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('412','Amaryl 3mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('413','Acotrust  Tablet');
insert into `medicines_csv` (`id`, `name`) values('414','Acupat Ophthalmic Solution');
insert into `medicines_csv` (`id`, `name`) values('415','Arcolane 2% Scalp Solution');
insert into `medicines_csv` (`id`, `name`) values('416','Atropine 1% Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('417','Amyclox-LB Capsule');
insert into `medicines_csv` (`id`, `name`) values('418','Alamin Injection');
insert into `medicines_csv` (`id`, `name`) values('419','Aquim PF Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('420','Arbitel-AM Tablet');
insert into `medicines_csv` (`id`, `name`) values('421','Aprecap 125/80 Capsule');
insert into `medicines_csv` (`id`, `name`) values('422','AB Phylline Syrup');
insert into `medicines_csv` (`id`, `name`) values('423','Azeflo FT Nasal Spray');
insert into `medicines_csv` (`id`, `name`) values('424','Atorva F Tablet');
insert into `medicines_csv` (`id`, `name`) values('425','Amicline Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('426','Acimol MR 100mg/325mg/250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('427','Abiways Tablet');
insert into `medicines_csv` (`id`, `name`) values('428','Asthakind Tablet');
insert into `medicines_csv` (`id`, `name`) values('429','Aprezo 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('430','Air 120 Tablet');
insert into `medicines_csv` (`id`, `name`) values('431','Amoxycillin  250mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('432','Acenac SP 100mg/325mg/15mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('433','Aginal-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('434','Allrite DC Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('435','Asthalin 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('436','Arip MT 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('437','Alcet 5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('438','Aplazar Tablet');
insert into `medicines_csv` (`id`, `name`) values('439','Amicon 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('440','Amaryl M Forte 1mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('441','Amicline Tablet');
insert into `medicines_csv` (`id`, `name`) values('442','Acivir IV Injection');
insert into `medicines_csv` (`id`, `name`) values('443','ATM 200 Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('444','Apidra Solostar 100IU/ml Injection');
insert into `medicines_csv` (`id`, `name`) values('445','AB2 Kit');
insert into `medicines_csv` (`id`, `name`) values('446','Amitryn 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('447','Atarax 25mg Injection');
insert into `medicines_csv` (`id`, `name`) values('448','Afoglip M  500 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('449','Amlozaar Tablet');
insert into `medicines_csv` (`id`, `name`) values('450','Abel 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('451','Acolate Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('452','Ampilox DS Tablet');
insert into `medicines_csv` (`id`, `name`) values('453','Asthalin Rotacaps');
insert into `medicines_csv` (`id`, `name`) values('454','Asthalin DX Syrup');
insert into `medicines_csv` (`id`, `name`) values('455','Asthalin Rotacaps');
insert into `medicines_csv` (`id`, `name`) values('456','Atorlip 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('457','Altacef 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('458','Amlokind 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('459','Ambistryn-S 0.75gm Injection');
insert into `medicines_csv` (`id`, `name`) values('460','Ambulax-ET Tablet');
insert into `medicines_csv` (`id`, `name`) values('461','Acceclowoc-P Tablet');
insert into `medicines_csv` (`id`, `name`) values('462','Alprax Forte 0.5 mg/50 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('463','Alsita-M 100 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('464','Axogurd NT Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('465','Aclind BP 2.5% Gel');
insert into `medicines_csv` (`id`, `name`) values('466','Anxiset 0.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('467','Atonide-H Cream');
insert into `medicines_csv` (`id`, `name`) values('468','Aldonil Tablet');
insert into `medicines_csv` (`id`, `name`) values('469','Anticold  Tablet');
insert into `medicines_csv` (`id`, `name`) values('470','Alcros 100 Capsule');
insert into `medicines_csv` (`id`, `name`) values('471','Azibact 200 Readymix Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('472','Atchol 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('473','Azibest 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('474','Amoxy 500mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('475','A-Ret 0.05% Gel');
insert into `medicines_csv` (`id`, `name`) values('476','Adenosine 3mg Injection');
insert into `medicines_csv` (`id`, `name`) values('477','Ascoril Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('478','Azulix 2 MF Forte Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('479','Amlokind-H Tablet');
insert into `medicines_csv` (`id`, `name`) values('480','Aziderm 10% Gel');
insert into `medicines_csv` (`id`, `name`) values('481','Amlopin-M Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('482','Ascodex Junior Syrup');
insert into `medicines_csv` (`id`, `name`) values('483','Alevo 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('484','Avanair 200 Tablet');
insert into `medicines_csv` (`id`, `name`) values('485','Atorlip 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('486','Anafortan-MF 50mg/250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('487','Amitriptyline Hcl 25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('488','Aqsusten  25 Solution for Injection');
insert into `medicines_csv` (`id`, `name`) values('489','Amicet 5 mg/60 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('490','Amrox Junior Syrup');
insert into `medicines_csv` (`id`, `name`) values('491','ATM 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('492','Anawin Heavy 5mg Injection');
insert into `medicines_csv` (`id`, `name`) values('493','Adaple-C Gel');
insert into `medicines_csv` (`id`, `name`) values('494','Aravon Injection');
insert into `medicines_csv` (`id`, `name`) values('495','Akilos-SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('496','Amlozaar-H Tablet');
insert into `medicines_csv` (`id`, `name`) values('497','Alight Plus Gel');
insert into `medicines_csv` (`id`, `name`) values('498','Anaspas 25mg Injection');
insert into `medicines_csv` (`id`, `name`) values('499','Azibact LR 100 Readymix');
insert into `medicines_csv` (`id`, `name`) values('500','Aquazide 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('501','Amlodac 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('502','Amoxclav 500 mg/125 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('503','Amplinak Opthalmic Suspension');
insert into `medicines_csv` (`id`, `name`) values('504','Aplevant 1.5mg Pre-filled Pen (0.5ml Each)');
insert into `medicines_csv` (`id`, `name`) values('505','Ambrodil-XP Syrup');
insert into `medicines_csv` (`id`, `name`) values('506','Arvast 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('507','Ascoril Flu Drops');
insert into `medicines_csv` (`id`, `name`) values('508','Atharv Healthcare Minrav 5 Minoxidil 5% Topical Solution');
insert into `medicines_csv` (`id`, `name`) values('509','Amoxyclav Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('510','Ata Mont 20mg/10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('511','Acimol 100 mg/325 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('512','Antidep 25mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('513','Artificial Tears BP Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('514','Almox 250 mg Tablet DT');
insert into `medicines_csv` (`id`, `name`) values('515','Azicip 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('516','Augpen HS 200 mg/28.5 mg Suspension');
insert into `medicines_csv` (`id`, `name`) values('517','Anfoe 10000IU Injection');
insert into `medicines_csv` (`id`, `name`) values('518','Acnovate Gel');
insert into `medicines_csv` (`id`, `name`) values('519','Ampoxin 250 Capsule');
insert into `medicines_csv` (`id`, `name`) values('520','Azibact LR Readymix 200');
insert into `medicines_csv` (`id`, `name`) values('521','Avanext 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('522','Anti-Thyrox 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('523','Aztor 80 Tablet');
insert into `medicines_csv` (`id`, `name`) values('524','Akair LC Tablet');
insert into `medicines_csv` (`id`, `name`) values('525','Azulix 1 Tablet');
insert into `medicines_csv` (`id`, `name`) values('526','Astymin-SN Infusion');
insert into `medicines_csv` (`id`, `name`) values('527','Asprito 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('528','Asomex-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('529','Anabel-CT Gel');
insert into `medicines_csv` (`id`, `name`) values('530','Amlovas 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('531','Amlovas H  Tablet');
insert into `medicines_csv` (`id`, `name`) values('532','Amodep 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('533','Acidose 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('534','AB-Next Gel');
insert into `medicines_csv` (`id`, `name`) values('535','Actapro Tablet');
insert into `medicines_csv` (`id`, `name`) values('536','Avas 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('537','Aqua Ear Drop');
insert into `medicines_csv` (`id`, `name`) values('538','Arflur-P Tablet');
insert into `medicines_csv` (`id`, `name`) values('539','Acnesol 1% solution');
insert into `medicines_csv` (`id`, `name`) values('540','Antiflu 12mg/ml Syrup');
insert into `medicines_csv` (`id`, `name`) values('541','Asiclopam Tablet');
insert into `medicines_csv` (`id`, `name`) values('542','Atorlip Gold 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('543','Amrox-LS Junior Syrup');
insert into `medicines_csv` (`id`, `name`) values('544','Alcarex Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('545','Amantex Tablet');
insert into `medicines_csv` (`id`, `name`) values('546','Acenac Tablet');
insert into `medicines_csv` (`id`, `name`) values('547','Adapen Gel');
insert into `medicines_csv` (`id`, `name`) values('548','Almefkem Spas 10mg/250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('549','Atonide Cream');
insert into `medicines_csv` (`id`, `name`) values('550','Amcard 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('551','AVENE (ABBOTT) 0.5mg/10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('552','Albutamol Neo Syrup');
insert into `medicines_csv` (`id`, `name`) values('553','Atchol-ASP Capsule');
insert into `medicines_csv` (`id`, `name`) values('554','Arbitel-H Tablet');
insert into `medicines_csv` (`id`, `name`) values('555','Aziderm 15% Gel');
insert into `medicines_csv` (`id`, `name`) values('556','Axcer  60mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('557','Abiways-M Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('558','Astymin-3  10mg/8mg Infusion');
insert into `medicines_csv` (`id`, `name`) values('559','Amlopres L Tablet');
insert into `medicines_csv` (`id`, `name`) values('560','Amifru Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('561','Armotraz Tablet');
insert into `medicines_csv` (`id`, `name`) values('562','Aldigesic TH 100mg/4mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('563','Abixim 200mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('564','Arbitel-MT 50 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('565','Aziderm 20% Gel');
insert into `medicines_csv` (`id`, `name`) values('566','Amiject 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('567','Azikem 250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('568','Aten-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('569','Altonil 5 Tablet MD');
insert into `medicines_csv` (`id`, `name`) values('570','Azipro 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('571','Addphos Granules');
insert into `medicines_csv` (`id`, `name`) values('572','Alkof LS Syrup');
insert into `medicines_csv` (`id`, `name`) values('573','Alsita 50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('574','Amlip 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('575','Apdrops KT 0.4 Eye Drops BAK Free');
insert into `medicines_csv` (`id`, `name`) values('576','Acimol Forte 100mg/325mg/15mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('577','Acnetor AD Gel');
insert into `medicines_csv` (`id`, `name`) values('578','Atocor 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('579','Angicam 5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('580','Aprezo 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('581','Asthakind-DX Syrup Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('582','Amitax 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('583','Actibile 150 Tablet');
insert into `medicines_csv` (`id`, `name`) values('584','Atorva Gold 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('585','Allercet Cold Syrup');
insert into `medicines_csv` (`id`, `name`) values('586','Alzero M Tablet');
insert into `medicines_csv` (`id`, `name`) values('587','Azulix 1 MF Forte Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('588','Azimax 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('589','Aloja 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('590','Arbitel-CT 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('591','Anthocyn-TX Tablet');
insert into `medicines_csv` (`id`, `name`) values('592','Actoid 25mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('593','Atocor 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('594','Ascoril Plus LS Expectorant');
insert into `medicines_csv` (`id`, `name`) values('595','Azulix 2 Tablet');
insert into `medicines_csv` (`id`, `name`) values('596','Aztor 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('597','Aziwok 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('598','Avastin 100mg Injection');
insert into `medicines_csv` (`id`, `name`) values('599','Acitrin 25mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('600','Antiblue 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('601','Arpimune ME 50mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('602','Azithral Tablet');
insert into `medicines_csv` (`id`, `name`) values('603','Ampiclox 250mg/250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('604','Analiv 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('605','Actifed 25 mg/2.5 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('606','Amlong A-25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('607','Azibact 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('608','Alendrate 70mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('609','Amrosys Cream');
insert into `medicines_csv` (`id`, `name`) values('610','Aminophylline 250mg Injection');
insert into `medicines_csv` (`id`, `name`) values('611','Ambrican 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('612','Arkamin H Tablet');
insert into `medicines_csv` (`id`, `name`) values('613','Alex-L Cough Syrup Mango Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('614','Atorfit 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('615','Alphagan P Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('616','Arzep Nasal Spray');
insert into `medicines_csv` (`id`, `name`) values('617','Angizem CD 90 Capsule ER');
insert into `medicines_csv` (`id`, `name`) values('618','Azovas 16mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('619','Advent 457mg Tablet DT');
insert into `medicines_csv` (`id`, `name`) values('620','Alcros 200 Capsule');
insert into `medicines_csv` (`id`, `name`) values('621','Amixide Tablet');
insert into `medicines_csv` (`id`, `name`) values('622','Aztogold 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('623','Alcoban 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('624','Arvast-A 75 Capsule');
insert into `medicines_csv` (`id`, `name`) values('625','Amlopin-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('626','Azilab 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('627','Amnuring 10 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('628','Ablung 200mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('629','Azusa 16 Tablet');
insert into `medicines_csv` (`id`, `name`) values('630','Afoglip Tablet');
insert into `medicines_csv` (`id`, `name`) values('631','Acefen SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('632','Aceclopar 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('633','Acotrust  OD 300mg Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('634','Avas 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('635','Acegaba NT 400mg/10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('636','Alerid Cold Tablet');
insert into `medicines_csv` (`id`, `name`) values('637','Acolate Tablet');
insert into `medicines_csv` (`id`, `name`) values('638','Antoxid E Softgel Capsule');
insert into `medicines_csv` (`id`, `name`) values('639','Agoprex Tablet');
insert into `medicines_csv` (`id`, `name`) values('640','Amlip 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('641','Alnitro 2.6 Tablet CR');
insert into `medicines_csv` (`id`, `name`) values('642','Alkem Piroxicam Injection');
insert into `medicines_csv` (`id`, `name`) values('643','Azithral Junior 200mg/5ml Drop');
insert into `medicines_csv` (`id`, `name`) values('644','Amtris Cream');
insert into `medicines_csv` (`id`, `name`) values('645','AF 300 Tablet');
insert into `medicines_csv` (`id`, `name`) values('646','Alaspan AG Syrup');
insert into `medicines_csv` (`id`, `name`) values('647','Asthalin AX JR Expectorant');
insert into `medicines_csv` (`id`, `name`) values('648','Abiways 200 SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('649','Atorva 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('650','Ambizyme 300mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('651','Acegrow 3D Tablet');
insert into `medicines_csv` (`id`, `name`) values('652','Alerfri Tablet');
insert into `medicines_csv` (`id`, `name`) values('653','Azee 500 Injection');
insert into `medicines_csv` (`id`, `name`) values('654','Azenam 1gm Injection');
insert into `medicines_csv` (`id`, `name`) values('655','Aceret 25 Capsule');
insert into `medicines_csv` (`id`, `name`) values('656','Alkarate Liquid');
insert into `medicines_csv` (`id`, `name`) values('657','Alprax Plus Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('658','Arachitol 3L Injection');
insert into `medicines_csv` (`id`, `name`) values('659','Alex Junior DS Syrup');
insert into `medicines_csv` (`id`, `name`) values('660','Amtas-M 25 Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('661','Anset 4mg Tablet MD');
insert into `medicines_csv` (`id`, `name`) values('662','Acecloren Tablet');
insert into `medicines_csv` (`id`, `name`) values('663','Atraxin 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('664','Atorva Gold 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('665','Amlong-TL 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('666','Apidra 100IU/ml Solution for Injection');
insert into `medicines_csv` (`id`, `name`) values('667','Apraize 30 Tablet');
insert into `medicines_csv` (`id`, `name`) values('668','Azithral 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('669','Ampoxin 1gm Injection');
insert into `medicines_csv` (`id`, `name`) values('670','Aspirin 300mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('671','Akurit Tablet');
insert into `medicines_csv` (`id`, `name`) values('672','Agna 10000 Capsule DR');
insert into `medicines_csv` (`id`, `name`) values('673','Alkashot B6 Oral Solution Delicious Pineapple Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('674','Ascoril Plus Expectorant Ginger Lemon');
insert into `medicines_csv` (`id`, `name`) values('675','Atormac Gold 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('676','Altonil Plus 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('677','Acimol-SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('678','Avas CV 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('679','Amlopres 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('680','Aceclowal P 100mg/500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('681','Airtec FB 400 Instacap');
insert into `medicines_csv` (`id`, `name`) values('682','Ablung 100mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('683','Alex Cold Syrup Berry');
insert into `medicines_csv` (`id`, `name`) values('684','Armod 50 Tablet');
insert into `medicines_csv` (`id`, `name`) values('685','Alcros SB 50 Capsule');
insert into `medicines_csv` (`id`, `name`) values('686','Ambrolite D Plus Syrup');
insert into `medicines_csv` (`id`, `name`) values('687','Alkem Cold 5 mg/500 mg/5 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('688','Azovas T 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('689','A-Ret 0.025% Gel');
insert into `medicines_csv` (`id`, `name`) values('690','Anafortan Drop');
insert into `medicines_csv` (`id`, `name`) values('691','Asomex-TM Tablet');
insert into `medicines_csv` (`id`, `name`) values('692','Aloatm 5% Solution');
insert into `medicines_csv` (`id`, `name`) values('693','Acekay Sera Tablet');
insert into `medicines_csv` (`id`, `name`) values('694','Alprax 1mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('695','Amoxible-CL 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('696','Alzil-M 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('697','Ageless Tablet');
insert into `medicines_csv` (`id`, `name`) values('698','Apdrops DM Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('699','Agycin 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('700','Aminowel Infusion');
insert into `medicines_csv` (`id`, `name`) values('701','Amnurite Beta 10/40 ER Tablet');
insert into `medicines_csv` (`id`, `name`) values('702','Asklerol 3% Injection');
insert into `medicines_csv` (`id`, `name`) values('703','Altonil 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('704','Atorlip Gold 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('705','Anti Druf Lotion');
insert into `medicines_csv` (`id`, `name`) values('706','Aceloflam Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('707','Altonil Plus 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('708','ACTEMRA 400 MG INJECTION');
insert into `medicines_csv` (`id`, `name`) values('709','Ampilox CV 500 mg/125 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('710','Alconol 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('711','Atchol CV Capsule');
insert into `medicines_csv` (`id`, `name`) values('712','Atormac Gold 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('713','Allegra 120mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('714','Acepar 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('715','Ampanel 4 Tablet');
insert into `medicines_csv` (`id`, `name`) values('716','Albutamol Syrup');
insert into `medicines_csv` (`id`, `name`) values('717','Aztor EZ Tablet');
insert into `medicines_csv` (`id`, `name`) values('718','Alfakit Tablet');
insert into `medicines_csv` (`id`, `name`) values('719','Atocor 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('720','Amitryn 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('721','Atormac CV 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('722','Amrofast Cream');
insert into `medicines_csv` (`id`, `name`) values('723','Arbitel-MT 25 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('724','Azithral-XL 100 Liquid');
insert into `medicines_csv` (`id`, `name`) values('725','Azi 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('726','Alphadopa Tablet');
insert into `medicines_csv` (`id`, `name`) values('727','Abz 400mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('728','Allerkast LC Tablet');
insert into `medicines_csv` (`id`, `name`) values('729','Amlodac T 40 mg/5 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('730','Ascodex DX Syrup');
insert into `medicines_csv` (`id`, `name`) values('731','Aerodil-LS Expectorant');
insert into `medicines_csv` (`id`, `name`) values('732','Absolut DM Capsule');
insert into `medicines_csv` (`id`, `name`) values('733','Azikind 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('734','Avoprost D 8mg/0.5mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('735','Arbitel-AV Tablet');
insert into `medicines_csv` (`id`, `name`) values('736','Amlopres-AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('737','Atorlip 80 Tablet');
insert into `medicines_csv` (`id`, `name`) values('738','Aquasurge  Max Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('739','Androgel');
insert into `medicines_csv` (`id`, `name`) values('740','Atocor-CV 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('741','Amnuring 5 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('742','Aldactone T 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('743','Ascodex Plus Syrup');
insert into `medicines_csv` (`id`, `name`) values('744','Addkay Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('745','Aggribloc 5mg Infusion');
insert into `medicines_csv` (`id`, `name`) values('746','Acotibien 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('747','Althrocin 100mg Drop');
insert into `medicines_csv` (`id`, `name`) values('748','Ambrodil-S Plus Syrup');
insert into `medicines_csv` (`id`, `name`) values('749','Alsita-M 100 Forte Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('750','Amoxil 250mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('751','Amicet Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('752','Azitus 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('753','Atorlip-ASP 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('754','Allegra 30mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('755','Acutrol C 400 Tablet');
insert into `medicines_csv` (`id`, `name`) values('756','Ace Proxyvon TH 4 Tablet');
insert into `medicines_csv` (`id`, `name`) values('757','Almefkem-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('758','Anfoe 4000IU Injection');
insert into `medicines_csv` (`id`, `name`) values('759','Auxerg Cream');
insert into `medicines_csv` (`id`, `name`) values('760','Ata Tablet');
insert into `medicines_csv` (`id`, `name`) values('761','Amisant 200 Tablet');
insert into `medicines_csv` (`id`, `name`) values('762','Allercet-L Tablet');
insert into `medicines_csv` (`id`, `name`) values('763','Andre Plus Eye Drops');
insert into `medicines_csv` (`id`, `name`) values('764','Arbitel 20 Tablet');
insert into `medicines_csv` (`id`, `name`) values('765','Acrotac 10mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('766','Ara Eye Gel');
insert into `medicines_csv` (`id`, `name`) values('767','Aginal 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('768','Amtas 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('769','Aricep 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('770','AD 10mg Sachet');
insert into `medicines_csv` (`id`, `name`) values('771','A Ret HC Cream');
insert into `medicines_csv` (`id`, `name`) values('772','Astin CV 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('773','Amodep 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('774','Arifine 2.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('775','Azithral 250mg DT Tablet');
insert into `medicines_csv` (`id`, `name`) values('776','Apilysin Syrup');
insert into `medicines_csv` (`id`, `name`) values('777','Acetik-HC Ear Drop');
insert into `medicines_csv` (`id`, `name`) values('778','Aricep-M  Tablet');
insert into `medicines_csv` (`id`, `name`) values('779','Airtec FB 200 Instacap');
insert into `medicines_csv` (`id`, `name`) values('780','Amoxy 250mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('781','Alorti Tablet');
insert into `medicines_csv` (`id`, `name`) values('782','App.UP Plus Syrup');
insert into `medicines_csv` (`id`, `name`) values('783','Atormac TG Tablet');
insert into `medicines_csv` (`id`, `name`) values('784','Azovas 8mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('785','Afoglip M  1000 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('786','Ambistryn-S 1gm Injection');
insert into `medicines_csv` (`id`, `name`) values('787','Anti Cold Syrup');
insert into `medicines_csv` (`id`, `name`) values('788','Anxipam 0.5mg Tablet MD');
insert into `medicines_csv` (`id`, `name`) values('789','Abmac Tablet');
insert into `medicines_csv` (`id`, `name`) values('790','Alkof Syrup Orange');
insert into `medicines_csv` (`id`, `name`) values('791','Anin Tablet');
insert into `medicines_csv` (`id`, `name`) values('792','Acnedap Plus Gel');
insert into `medicines_csv` (`id`, `name`) values('793','Apresol Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('794','Azulix MV 2mg/500mg/0.3mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('795','Ace-Proxyvon SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('796','Angistat 2.5 Capsule TR');
insert into `medicines_csv` (`id`, `name`) values('797','Anafortan N 100 mg/50 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('798','Atorlip CV Capsule');
insert into `medicines_csv` (`id`, `name`) values('799','Anozest Cream');
insert into `medicines_csv` (`id`, `name`) values('800','Amoxil 250mg Tablet DT');
insert into `medicines_csv` (`id`, `name`) values('801','Acemiz 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('802','Alrista Plus Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('803','Ascapil 12A Tablet DT');
insert into `medicines_csv` (`id`, `name`) values('804','Addex 500mg Ointment');
insert into `medicines_csv` (`id`, `name`) values('805','Acetik Ear Drop');
insert into `medicines_csv` (`id`, `name`) values('806','Aisa  Tablet');
insert into `medicines_csv` (`id`, `name`) values('807','Acolate P Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('808','Airz-F Digihaler');
insert into `medicines_csv` (`id`, `name`) values('809','Anleo-DSR Capsule');
insert into `medicines_csv` (`id`, `name`) values('810','Aladrine 2.5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('811','Azarga Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('812','Amlopres 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('813','Anti-Thyrox 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('814','Anthocyn-TX Cream');
insert into `medicines_csv` (`id`, `name`) values('815','Anomed L Cream');
insert into `medicines_csv` (`id`, `name`) values('816','Ampoxin-CV 500mg/125mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('817','Azilide 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('818','App UP Syrup');
insert into `medicines_csv` (`id`, `name`) values('819','Apraize 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('820','Alkasol Oral Solution Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('821','Abirapro 250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('822','Acolate Kid Syrup Mango');
insert into `medicines_csv` (`id`, `name`) values('823','Androtas Gel');
insert into `medicines_csv` (`id`, `name`) values('824','Atorec-ASP Capsule');
insert into `medicines_csv` (`id`, `name`) values('825','Aziwok 100 Liquid');
insert into `medicines_csv` (`id`, `name`) values('826','Amitryn-C Tablet');
insert into `medicines_csv` (`id`, `name`) values('827','Azee 1000 Tablet');
insert into `medicines_csv` (`id`, `name`) values('828','Adefresh 400 Tablet');
insert into `medicines_csv` (`id`, `name`) values('829','Abphylin 100mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('830','Adriamycin 50mg Injection');
insert into `medicines_csv` (`id`, `name`) values('831','Azulix MV 2/0.2 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('832','Absolut DM Capsule');
insert into `medicines_csv` (`id`, `name`) values('833','Ambrodil-XP Capsule');
insert into `medicines_csv` (`id`, `name`) values('834','Augxetil 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('835','Adiff Gel');
insert into `medicines_csv` (`id`, `name`) values('836','Augplat 250mcg Injection');
insert into `medicines_csv` (`id`, `name`) values('837','Actiheal-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('838','Adilip 45 Tablet DR');
insert into `medicines_csv` (`id`, `name`) values('839','Adalipca 40mg Injection');
insert into `medicines_csv` (`id`, `name`) values('840','Alfa GPC Tablet');
insert into `medicines_csv` (`id`, `name`) values('841','Atracurium Besilate Injection');
insert into `medicines_csv` (`id`, `name`) values('842','Ambropil BR Syrup');
insert into `medicines_csv` (`id`, `name`) values('843','Andriol 40mg Testocap');
insert into `medicines_csv` (`id`, `name`) values('844','ANALGIN 500MG TABLET');
insert into `medicines_csv` (`id`, `name`) values('845','Asprito 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('846','Accuzon 1g Injection');
insert into `medicines_csv` (`id`, `name`) values('847','Atrest 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('848','Amlodac M Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('849','Amicin 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('850','Atocor Gold 20 Capsule');
insert into `medicines_csv` (`id`, `name`) values('851','Atocor 80 Tablet');
insert into `medicines_csv` (`id`, `name`) values('852','Actifed Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('853','Alcinac P 100mg/325mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('854','Arpizol 15 Tablet');
insert into `medicines_csv` (`id`, `name`) values('855','Arigaba NT Tablet');
insert into `medicines_csv` (`id`, `name`) values('856','Acivir 400mg Syrup');
insert into `medicines_csv` (`id`, `name`) values('857','Amlomed AT 5mg/50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('858','Azusa T 8/40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('859','Azomycin 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('860','Abortab 200mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('861','Aldryl Syrup');
insert into `medicines_csv` (`id`, `name`) values('862','Azibact 100 Readymix Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('863','Accuzon Plus 1.5gm Injection');
insert into `medicines_csv` (`id`, `name`) values('864','Anaproct Ointment');
insert into `medicines_csv` (`id`, `name`) values('865','Attentrol 10mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('866','Amace Tablet');
insert into `medicines_csv` (`id`, `name`) values('867','Aciloc-S Suspension Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('868','Ara Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('869','Aziwok-XL 200 Liquid');
insert into `medicines_csv` (`id`, `name`) values('870','Aim7 60 XR Tablet');
insert into `medicines_csv` (`id`, `name`) values('871','Atchol Gold 10 Capsule');
insert into `medicines_csv` (`id`, `name`) values('872','Acenac-P  Tablet');
insert into `medicines_csv` (`id`, `name`) values('873','Amortas Cream');
insert into `medicines_csv` (`id`, `name`) values('874','Aldonil Plus Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('875','Auxerg Cream');
insert into `medicines_csv` (`id`, `name`) values('876','Acotrust  Tablet');
insert into `medicines_csv` (`id`, `name`) values('877','Aldep 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('878','AT SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('879','Anxol Tablet');
insert into `medicines_csv` (`id`, `name`) values('880','Aricef O 50mg/5ml Dry Syrup');
insert into `medicines_csv` (`id`, `name`) values('881','Addwize OD 18mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('882','Amipride 50 Tablet');
insert into `medicines_csv` (`id`, `name`) values('883','Altiva 120mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('884','Aclon-SP Tablet');
insert into `medicines_csv` (`id`, `name`) values('885','Allenza Tablet');
insert into `medicines_csv` (`id`, `name`) values('886','Amrolmac Cream');
insert into `medicines_csv` (`id`, `name`) values('887','Atrovas 40mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('888','Amtas 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('889','Alpostin 500mcg Injection');
insert into `medicines_csv` (`id`, `name`) values('890','Alka-PH Syrup');
insert into `medicines_csv` (`id`, `name`) values('891','Amlokind Beta 5mg/25mg Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('892','Afogatran 110 Capsule');
insert into `medicines_csv` (`id`, `name`) values('893','Auradex 4mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('894','Ancool  SF Suspension');
insert into `medicines_csv` (`id`, `name`) values('895','Aggramed 5mg Infusion');
insert into `medicines_csv` (`id`, `name`) values('896','Acetamide 250mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('897','Agmacet 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('898','Amloz AT Tablet');
insert into `medicines_csv` (`id`, `name`) values('899','Aerodil-DX Syrup Raspberry Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('900','Arip MT 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('901','Alivher ES Tablet');
insert into `medicines_csv` (`id`, `name`) values('902','Amrfy 0.25% Cream');
insert into `medicines_csv` (`id`, `name`) values('903','Amrobrut Cream');
insert into `medicines_csv` (`id`, `name`) values('904','Ace Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('905','Advent 228.5mg Dry Syrup');
insert into `medicines_csv` (`id`, `name`) values('906','Alides 5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('907','Alastin AM Tablet');
insert into `medicines_csv` (`id`, `name`) values('908','Ascodex SF Syrup Sugar Free');
insert into `medicines_csv` (`id`, `name`) values('909','Amclaid 625 Tablet');
insert into `medicines_csv` (`id`, `name`) values('910','Aloederm F Cream');
insert into `medicines_csv` (`id`, `name`) values('911','Avoprost 8mg Capsule');
insert into `medicines_csv` (`id`, `name`) values('912','Amiline 10mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('913','Arvast F 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('914','Anin 500mg Injection');
insert into `medicines_csv` (`id`, `name`) values('915','Amloz 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('916','Azulix 4 MF Forte Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('917','Amtas-AT 25 Tablet');
insert into `medicines_csv` (`id`, `name`) values('918','Arophyll HD 10mg/120mg/200mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('919','Alcaft Eye Drop');
insert into `medicines_csv` (`id`, `name`) values('920','Acitrom 0.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('921','Asar 40 Tablet');
insert into `medicines_csv` (`id`, `name`) values('922','Anxit 0.5 SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('923','Alkazip Syrup');
insert into `medicines_csv` (`id`, `name`) values('924','Afoglip M  500 Tablet ER');
insert into `medicines_csv` (`id`, `name`) values('925','Arvast-CF 10 Capsule DR');
insert into `medicines_csv` (`id`, `name`) values('926','AUGMENTIN 375 DUO TABLET');
insert into `medicines_csv` (`id`, `name`) values('927','Actrapid 100IU/ml Solution for Injection');
insert into `medicines_csv` (`id`, `name`) values('928','Axinerve-P Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('929','Adiflam Plus 400 mg/500 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('930','Amitop M 5mg/1500mcg Tablet');
insert into `medicines_csv` (`id`, `name`) values('931','Asomex-D Tablet');
insert into `medicines_csv` (`id`, `name`) values('932','Azro 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('933','Answell 400 mg/325 mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('934','Acenext 100mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('935','Advent 1.2gm  Injection');
insert into `medicines_csv` (`id`, `name`) values('936','AZILUP 500 MG TABLET');
insert into `medicines_csv` (`id`, `name`) values('937','Aceron TC Tablet');
insert into `medicines_csv` (`id`, `name`) values('938','Aldigesic-Rab Capsule SR');
insert into `medicines_csv` (`id`, `name`) values('939','ACTION OR 1000mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('940','Adilin 40mg Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('941','Abhayrab-PF Vaccine');
insert into `medicines_csv` (`id`, `name`) values('942','Amlodac 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('943','Alfalog Tablet');
insert into `medicines_csv` (`id`, `name`) values('944','Azax 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('945','Azifast Gel');
insert into `medicines_csv` (`id`, `name`) values('946','Amlovas-L Tablet');
insert into `medicines_csv` (`id`, `name`) values('947','Atorsave D 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('948','Amfy V  Vaginal gel');
insert into `medicines_csv` (`id`, `name`) values('949','AMIT 10 MG TABLET');
insert into `medicines_csv` (`id`, `name`) values('950','Alex P Paed Drop');
insert into `medicines_csv` (`id`, `name`) values('951','Azivent 250 Tablet');
insert into `medicines_csv` (`id`, `name`) values('952','Alto\'s Citrasol Liquid');
insert into `medicines_csv` (`id`, `name`) values('953','Amorfine Cream');
insert into `medicines_csv` (`id`, `name`) values('954','Azapure Tablet');
insert into `medicines_csv` (`id`, `name`) values('955','Akme-Entoquol Tablet');
insert into `medicines_csv` (`id`, `name`) values('956','Amrolmac Cream');
insert into `medicines_csv` (`id`, `name`) values('957','Atherochek 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('958','Axepta 18mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('959','Alconil 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('960','Ascodex D Syrup');
insert into `medicines_csv` (`id`, `name`) values('961','Angiplat 6.5 Capsule TR');
insert into `medicines_csv` (`id`, `name`) values('962','Adfrar Injection');
insert into `medicines_csv` (`id`, `name`) values('963','Ambrox T Syrup');
insert into `medicines_csv` (`id`, `name`) values('964','Aciloc Only Oral Liquid');
insert into `medicines_csv` (`id`, `name`) values('965','Azunate 60mg Injection');
insert into `medicines_csv` (`id`, `name`) values('966','Acton-OR Plus+ Tablet');
insert into `medicines_csv` (`id`, `name`) values('967','Amikacin 250mg Injection');
insert into `medicines_csv` (`id`, `name`) values('968','Accardi MR Tablet MR');
insert into `medicines_csv` (`id`, `name`) values('969','Acenac-SR Tablet');
insert into `medicines_csv` (`id`, `name`) values('970','Albutamol Plus Tablet');
insert into `medicines_csv` (`id`, `name`) values('971','Azirin 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('972','Azusa 8mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('973','Amlodac CH Tablet');
insert into `medicines_csv` (`id`, `name`) values('974','Atorec 10 Tablet');
insert into `medicines_csv` (`id`, `name`) values('975','Azilide 100 RediMed Oral Suspension');
insert into `medicines_csv` (`id`, `name`) values('976','Alkanil Syrup');
insert into `medicines_csv` (`id`, `name`) values('977','Atrest 12.5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('978','Abvida 50mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('979','Azee XL 100mg Dry Syrup Peppermint');
insert into `medicines_csv` (`id`, `name`) values('980','ASA 75mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('981','Amnurite  25 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('982','Atorlip 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('983','Acnetoin Plus Gel');
insert into `medicines_csv` (`id`, `name`) values('984','Amlovas-M 5/25 Tablet PR');
insert into `medicines_csv` (`id`, `name`) values('985','Aziford 500mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('986','Anglit 2.6 Tablet CR');
insert into `medicines_csv` (`id`, `name`) values('987','Amlogard 2.5mg Tablet');
insert into `medicines_csv` (`id`, `name`) values('988','Amdepin 5 Tablet');
insert into `medicines_csv` (`id`, `name`) values('989','AB-Resp Tablet');
insert into `medicines_csv` (`id`, `name`) values('990','Amiodar 200 Tablet');
insert into `medicines_csv` (`id`, `name`) values('991','Amazeo OD 100 Tablet SR');
insert into `medicines_csv` (`id`, `name`) values('992','Alzero M Syrup');
insert into `medicines_csv` (`id`, `name`) values('993','Acocontin Tablet CR');
insert into `medicines_csv` (`id`, `name`) values('994','Alphacept 8 Tablet');
insert into `medicines_csv` (`id`, `name`) values('995','Azithral XL 200 Liquid');
insert into `medicines_csv` (`id`, `name`) values('996','Altime CF Syrup');
insert into `medicines_csv` (`id`, `name`) values('997','Augxetil CV 500 Tablet');
insert into `medicines_csv` (`id`, `name`) values('998','Ambrolite Cold Syrup');
insert into `medicines_csv` (`id`, `name`) values('999','Altonil Syrup');
insert into `medicines_csv` (`id`, `name`) values('1000','Asolt-AT Tablet');
